name: Update output.html

on:
  push:
    branches:
      - main  # Only trigger on pushes to the main branch
    paths-ignore:  # Ignore changes to workflow files
      - '.github/workflows/**'

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Image URL from Commit Message
      run: |
        commitMessage=$(git log -1 --pretty=%B)  # Get the commit message
        if [[ "$commitMessage" =~ https:\/\/.* ]]; then  # Check if the commit message contains a URL
          imageUrl=$(echo "$commitMessage" | grep -o 'https:\/\/.*')  # Extract URL
          echo $imageUrl > imageUrl.txt
        else
          exit 1  # Exit with error if no URL is found
        fi

    - name: Update output.html
      run: |
        imageUrl=$(cat imageUrl.txt)  # Read the image URL from the file
        echo "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Unsplash Image URL</title></head><body><p>${imageUrl}</p></body></html>" > output.html

    - name: Commit and push changes
      run: |
        git add output.html
        git commit -m "Update output.html"
        git push origin main
