name: Update output.html

on:
  push:
    branches:
      - main  # Action triggers when pushing to this branch

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update output.html
      run: |
        imageUrl=$(git log -1 --pretty=%B | grep -o 'https:\/\/.*')  # Extracts URL from commit message
        if [ -z "$imageUrl" ]; then
            echo "No image URL found in the commit message"
            exit 1  # Exit the workflow with a non-zero code to indicate failure
        fi
        echo "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Unsplash Image URL</title></head><body><p>${imageUrl}</p></body></html>" > output.html

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output.html
        git commit -m "Update output.html with new image URL: $imageUrl"  # Commit with new image URL
        git push origin main

